### ISSUE TITLE
Document "infrastructure"

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/contributors#4]
List of "infrastructure" we use and short description of it and how it "administer".

- GitHub
- GitHub actions
- CirrusCI
- Zapier
- Zulip
- DockerHub
- Netlify
- 1Password
- Zoom
- Cloudsmith
- forward.io
- Linode

and whatever else that should be on the list

**Comment by damon-kwok** [comment]
Melpa : `ponylang-mode`.

**Comment by damon-kwok** [comment]
Twitter: @ponylang
